### ISSUE TITLE
[BUG] cMenu sticks to body of first pane only

### ISSUE THREAD

**Issue by firinael** [chetachiezikeuzor/cMenu-Plugin#8]
Basically, cMenu, when used with sliding panes and body-sticking, sticks only to the very first pane, no matter what is its state.

gfycat link below demonstrates the issue:
https://gfycat.com/fatherlyhighlevelcattle

**Comment by chetachiezikeuzor** [comment]
Have you already toggled "body" for the append method? And then regenerated it?

**Comment by chetachiezikeuzor** [comment]
So you toggled "body" as the append method and regenerated it? As in you've closed out the panes?

**Comment by firinael** [comment]
Yes, already both closed all panes and reopened them, and forced a refresh of the app.

**Comment by firinael** [comment]
Wait, my mistake, I got mixed up, but the bug is even weirder than I'd expected.

What happens is: 

Having "workspace" toggled makes it stick to the body, but only the first pane, and doesn't make it disappear when exiting edit mode.

Having "body" toggled makes it stick to the workspace, and still doesn't disappear when exiting edit mode.

It's bizarre.

**Comment by chetachiezikeuzor** [comment]
It shouldn't disappear when you change to preview mode. I'm still trying to figure out the best way to go about doing that since removed and appending elements to the DOM is a pretty *expensive* endeavor. But I'm not seeing the issue you're raising in the video you've sent. Maybe I'm missing something?

**Comment by chetachiezikeuzor** [comment]
This is how it should be working

https://user-images.githubusercontent.com/79069364/129273995-61a96ed8-5496-4fea-97ef-c06c4b17f174.mp4

**Comment by firinael** [comment]
Oh wow I think it's a massive misunderstanding on my end, then? By "workspace", I thought it'd remain on-screen at all times, and thought that "body" would mean it'd stay stuck to the body of the pane you're editing.

Anyways, my mistake. But if I may recommend some UX/QoL changes, having cMenu disappear when there is no Editor pane focused (that is, clicked/active) would be best (in my opinion).

Also ***how did you change your dropdown to be that pretty??*** or is that a MacOS thing?

**Comment by chetachiezikeuzor** [comment]
Yea, I know it would be better to have cMenu only on Editor, that's why I'm currently working on it! Obsidian's API documentation isn't very specific on what I can and can't use, and I don't want to end up impacting other plugins or have cMenu fail to regenerate on a view. So I'm still testing a few things. And I think it is a macOS thing.

**Comment by firinael** [comment]
I'm guessing that setting display: none when not in a writing field isn't a good solution?

**Comment by chetachiezikeuzor** [comment]
I guess I'm not explaining properly. I'm not talking about the property to be applied, I'm talking about the event to use, what indicates that you aren't in editor.

**Comment by firinael** [comment]
ah yeah that's an entirely different issue, then.

anyways, sorry for the misunderstanding, and thanks for your hard work!
